Add Modal.js + Add global z-index scale
locomotivemtl/locomotive-boilerplate pull request #100
Opened 2021-11-01 20:15 UTC by mcaskill

Add accessible modal dialog component and ordered z-index map to standardize the layering of our components.

Dialog Features:

- Dialog supports being shown on page load via `data-modal-autoshow` attribute.
- Dialog supports being shown at most once via the `data-modal-show-once` attribute.
- Dialog persists dismissal via `localStorage`, by default. This can be switched to `sessionStoage` via `data-modal-show-once="session"` attribute value.
- When Load handles "loading" event, executes `Modal.hide` on all shown modals.

Required:

- NPM dependency [a11y-dialog v7.3.0](https://github.com/KittyGiraudel/a11y-dialog/releases/tag/7.3.0)

Added:

- JS class `Modal` that uses and enhances a11y-dialog.
- CSS component `.c-dialog` via partial '_modal.scss' with basic styles (adapted from vendor's [example](https://codesandbox.io/s/a11y-dialog-pnwqu?file=/src/styles.css)).
- Basic HTML example of `data-module-modal`.
- Default Sass z-index scale `$overlay-zindexes`: dropdown, sticky, fixed, offcanvas, modal, popover, tooltip, transition.
- Sass function `overlay-zindex()` to fetch the z-index for the corresponding element (based on [OZMap](https://rafistrauss.com/blog/ordered_z_index_maps)).

2021-11-02 14:40 UTC, devenini requested changes

2021-11-02 14:40 UTC, devenini commented on www/modal.html
> +                <div class="c-dialog_container"
I would advice to put the markup of `c-dialog_container` outside the `<div class="o-scroll">`. If no `data-scroll-section` are specified, then the o-scroll "becomes" the scroll-section and a transform will be applied on the element preventing all children with position `fixed` to work properly

2021-11-02 14:40 UTC, devenini commented on www/modal.html
> +        <style type="text/css">
Not convinced of having internal styles in the boilerplate. I'm guessing this is because our reset kills the native button/link styles?

2021-11-02 14:40 UTC, devenini commented
Overall I like the idea of building re-usable components. I'm just not sure if the boilerplate is the best place to put these tools. I think a "playground/demo type" repo with all the components would be best. Since this repo is our project starter and that means we will have to clean/remove all unused components.

2022-03-24 14:02 UTC, mcaskill commented
Closing in favour of moving this component to [locomotivemtl/cookbook#7](https://github.com/locomotivemtl/cookbook/issues/7).

2022-03-24 14:02 UTC, closed without merging