Mediaqueries update
locomotivemtl/locomotive-boilerplate pull request #116
Opened 2022-05-20 09:19 UTC by lucasvallenet

## Description:

Update the media queries system with a scss list.
This is going to lighten the scss syntax and prevent media queries mistakes (ex: `@media (min-width: $to-large)`). It will also allow us to loop through each breakpoints to create utility classes for example.
I created two functions to retreive the desired mediaquery: 

1. `md($breakpoint, $type: "min")`: 
     Min/Max media query using the breakpoint key (`tiny|small|medium|...`) and type (`min|max`) default set to `min`.
3. `mdb($breakpointMin, $breakpointMax)`: 
      Media query between range using two breakpoint keys, with min and max value

## Use:

**Old syntax**
```
@media (min-width: $from-large) { ... }
@media (max-width: $to-large) { ... }
@media (min-width: $from-small) and (max-width: $to-large) { ... }
````

**New syntax**
```
@media #{md("large'')} { ... }
@media #{md("large'', "max)} { ... }
@media #{mdb("small', "large')} { ... }
```

## Advantage:
The scss list allows us to loop through each breakpoints to create utility classes

**Example**
```
@each $breakpoint in $breakpoints {
    $key: nth($breakpoint, 1);
    $bp: nth($breakpoint, 2);

    // Media queries min
    @media #{md($key)} {
        $modifier: \@#{$key};
        .u-display-block#{$modifier} {
            display: block; !important
        }
    }

    // Media queries max
    @media #{md($key, "max")} {
        $modifier: \@#{$key}-max;
        .u-display-block#{$modifier} {
            display: block; !important
        }
    }
}
```

This will return a class for each breakpoint like so:
`.u-display-block@small` and `.u-display-block@small-max`

The media query syntax might not be the clearest but I didn't find another way to use a scss function following a `@media`.
The main advantage is to be able to loop through each breakpoints.
The functions names `md` and `mdb` refers to media query and media query between, they can be updated if you have a better name.

2022-05-20 16:01 UTC, mcaskill requested changes
I like this but I'm not a fan of the function names, kind of vague.

If I recall, we used to use [sass-mq](https://github.com/sass-mq/sass-mq) which is a solid mixin library. I had made improvements in a [fork](https://github.com/mcaskill/sass-mq) that made it work more like what you are proposing.

2022-05-25 13:58 UTC, mcaskill approved these changes

2022-10-05 12:15 UTC, devenini commented
Hello! It didn't work straight away on my side. I pushed a fix that update the functions names and I corrected typos inside the SCSS functions.

I like the idea of using `scss` function for our media queries. I think the function names are clear and I can see myself using this utils. Vouched.

2022-10-05 15:01 UTC, mcaskill commented
#### Outcome from meeting on 2022-10-05

* **Status**: On hold until further notice.
* Jeremy and Lucas B. disapproves of the overly complicated string interpolated syntax.
* Deven likes the proposal. With IDE snippets, this can be useful.
* Lucas V., and most, appreciate the proposed ability to iterate predefined media queries.

2022-10-05 18:54 UTC, arnvvd approved these changes

2022-10-06 15:00 UTC, devenini approved these changes

2023-12-11 10:03 UTC, closed without merging