Update compilation 2020
locomotivemtl/locomotive-boilerplate pull request #79
Opened 2021-03-04 16:57 UTC by quentinhocde

- Remove gulp (using node scripts)
- Remove es5 support
- Add esbuild
- Rewrite tasks
- Keep mconfig.json from modularBP

2021-03-04 17:10 UTC, mcaskill commented
Can something like ESLint be installed and applied to files to normalize our coding style?
There's quite a bit of superfluous blank lines, inconsistent indentation, missing white space (such as after commas), and other details which reduce readability.

2021-03-04 17:11 UTC, mcaskill commented
Also, ensure the `.editorconfig` is in sync with the Charcoal boilerplate and that those rules are applied to this boilerplate.

2021-03-04 17:25 UTC, Jerek0 approved these changes

2021-03-04 21:44 UTC, mcaskill requested changes
#### package.json, package-lock.json, mconfig.json

Files should adhere to a 4-space indentation as per `.editorconfig`.

#### assets/scripts/app.js

The [app.js](https://github.com/locomotivemtl/locomotive-boilerplate/blob/update-compilation-2020/assets/scripts/app.js) contains inconsistent string quotation characters.

```diff
-    const $style = document.getElementById("stylesheet");
+    const $style = document.getElementById('stylesheet');
```

This ID should maybe be dynamic or reflect the name of the stylesheet file name, similar to what WordPress does for its enqueued styles.

```diff
-    const $style = document.getElementById('stylesheet');
+    const $style = document.getElementById('main-css');
```

#### assets/scripts/modules/Scroll.js

The [Scroll.js](https://github.com/locomotivemtl/locomotive-boilerplate/blob/update-compilation-2020/assets/scripts/modules/Scroll.js) contains inconsistent coding styles.

```diff
-            if(args.obj.el.tagName == "IMG") {
-                args.obj.el.src = src
-            } else {
-                args.obj.el.style.backgroundImage = `url(${src})`
-            }
+            if (args.obj.el.tagName === 'IMG') {
+                args.obj.el.src = src
+            } else {
+                args.obj.el.style.backgroundImage = `url('${src}')`
+            }
```

2021-03-04 21:44 UTC, mcaskill commented on .editorconfig
>  indent_style = space
```suggestion
```

This segment can be removed since it does not change from the initial rules.

2021-03-04 21:44 UTC, mcaskill commented on README.md
> +[Node]:         https://nodejs.org/en/
```suggestion
| Name       | Version  |
| ---------- | -------- |
| [Node]     | > 14.15  |

[Node]:         https://nodejs.org/en/
```

2021-03-04 21:44 UTC, mcaskill commented on assets/scripts/modules/Load.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on assets/scripts/modules/Scroll.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on build/concat.js
> +    });
```suggestion
    // Exclude files that are not JavaScript
    var jsFiles = files.filter((file) => {
        return file.includes('.js');
    });

    // Prepend absolute path
    jsFiles = jsFiles.map((file) => {
        return `${paths.scripts.vendors.src + file}`;
    });
```

The `String.prototype.includes()` method returns a boolean, no need for `if else`.

2021-03-04 21:44 UTC, mcaskill commented on build/concat.js
> +
```suggestion

```

2021-03-04 21:44 UTC, mcaskill commented on build/concat.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on build/concat.js
> +  }
```suggestion
}
```

2021-03-04 21:44 UTC, mcaskill commented on build/notification.js
> +export default function notification({title, message}) {
```suggestion
export default function notification({ title, message }) {
```

2021-03-04 21:44 UTC, mcaskill commented on build/scripts.js
> +        entryPoints: [paths.scripts.src + paths.scripts.main + '.js'],
```suggestion
        entryPoints: [ paths.scripts.src + paths.scripts.main + '.js' ],
```

2021-03-04 21:44 UTC, mcaskill commented on build/scripts.js
> +        target: ['es2015'],
```suggestion
        target: [ 'es2015' ],
```

2021-03-04 21:44 UTC, mcaskill commented on build/scripts.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on build/styles.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on build/styles.js
> +        if(error) {
```suggestion
        if (error) {
```

2021-03-04 21:44 UTC, mcaskill commented on build/styles.js
> +        if(error) {
```suggestion
        if (error) {
```

2021-03-04 21:44 UTC, mcaskill commented on build/styles.js
> +          }
```suggestion
        if (!error){
            // No errors during the compilation, write this result on the disk
            fs.writeFile(paths.styles.dest + paths.styles.main + '.css', result.css, (err) => {});
        }
```

2021-03-04 21:44 UTC, mcaskill commented on build/styles.js
> +          }
```suggestion
        if (!error){
            // No errors during the compilation, write this result on the disk
            fs.writeFile(paths.styles.dest + paths.styles.critical + '.css', result.css, (err) => {});
        }
```

2021-03-04 21:44 UTC, mcaskill commented on build/svgs.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on build/svgs.js
> +    });
```suggestion
    mixer([
        paths.svgs.src + '*.svg'
    ], {
        spriteConfig: {
            usages: false
        }
    }).then((result) => {
        result.write(paths.svgs.dest + 'sprite.svg');
        message('SVG Sprite generated', 'success', 'Sprite generated in');
    });
```

2021-03-04 21:44 UTC, mcaskill commented on build/utils/message.js
> +
```suggestion
```

2021-03-04 21:44 UTC, mcaskill commented on build/utils/message.js
> +    }
```suggestion
    if (type === 'success') {
        console.log(kleur.bgGreen().black(`${text} ✅`));

        if (timerId !== undefined) {
            console.timeEnd(timerId)
        }
    } else if (type === 'error') {
        console.log(kleur.red().underline(`${text} ❌`));
    } else if (type === 'waiting') {
        console.log(kleur.blue().italic(`${text} ⏱`));
    } else {
        console.log(text);
    }
```

2021-03-04 21:44 UTC, mcaskill commented on package.json
> +  "engines": { "node": "???" },
```suggestion
  "engines": {
    "node": "^14.15"
  },
```

This should reflect the version defined in the `.nvmrc`.

2021-03-05 14:32 UTC, quentinhocde commented
Thanks @mcaskill, I fix everything in your review :)

2021-03-05 14:37 UTC, mcaskill approved these changes

2021-03-05 14:39 UTC, devenini approved these changes

2021-03-05 14:42 UTC, arnvvd approved these changes

2021-03-05 14:44 UTC, merged